modules:
  http_admin:
    prober: http
    timeout: 10s
    http:
      method: GET
      fail_if_not_ssl: true
      preferred_ip_protocol: ip4
  websocket_admin:
    prober: http
    timeout: 10s
    http:
      method: GET
      fail_if_not_ssl: true
      valid_status_codes: [101]
      headers:
        Connection: "Upgrade"
        Upgrade: "websocket"
      preferred_ip_protocol: ip4
